In [0]:
import pandas as pd
data = pd.read_csv('aaa.csv')
data

    #csv를 지번코드로 인덱스해보자
indices = pd.Series(data.index, index = data['지번코드']).drop_duplicates()
    # index 앞과 뒤를 봐보자
indices.head()
indices.tail()

    #scv를 유사도 계산할때 필요한 부분만 잘라보자
#sliceData = data.iloc[:,2:26]
sliceData=data.iloc[:,26:51]
#print(sliceData)

    #자른 부분에서 0행과 1행만 array로 바꾸고 코사인유사도계산해보자
from numpy import dot
from numpy.linalg import norm
import numpy as np


slice1 = sliceData[0:1]
doc1 = np.array(slice1)
slice2 = sliceData[1:2]
doc2 = np.array(slice2)
print(doc1)
print(doc2)

def cos_sim(A, B):
    return dot(A,B)/(norm(A)*norm(B))

[[0.00109205 0.00103574 0.00097519 0.00096906 0.00114616 0.00140302
  0.00121903 0.0011575  0.00111004 0.00106263 0.00104828 0.00105144
  0.00102696 0.00107791 0.00109855 0.00107499 0.00107984 0.00105927
  0.00107331 0.00111932 0.00112114 0.00110409 0.00112681 0.00114392]]
[[0.0010027  0.00102226 0.00100814 0.00092742 0.00111038 0.0011305
  0.00095846 0.00078799 0.00079463 0.00087922 0.00105004 0.00115878
  0.00127581 0.00136324 0.00140658 0.00135853 0.0012994  0.00122441
  0.00119074 0.00127977 0.00132578 0.00125702 0.00116065 0.00104988]]


In [0]:
doc1.shape

(1, 24)

In [0]:
doc2.shape

(1, 24)

In [0]:
# dot product 하기 위해 Trans해줘야함
doc2 = doc2.reshape(24,1)

In [0]:
doc2

array([[0.0010027 ],
       [0.00102226],
       [0.00100814],
       [0.00092742],
       [0.00111038],
       [0.0011305 ],
       [0.00095846],
       [0.00078799],
       [0.00079463],
       [0.00087922],
       [0.00105004],
       [0.00115878],
       [0.00127581],
       [0.00136324],
       [0.00140658],
       [0.00135853],
       [0.0012994 ],
       [0.00122441],
       [0.00119074],
       [0.00127977],
       [0.00132578],
       [0.00125702],
       [0.00116065],
       [0.00104988]])

In [0]:
cos_sim(doc1,doc2)

array([[0.98489086]])

In [0]:
#slice data 전체를 하나의 행렬에 넣어보자
matrix_data = np.array(sliceData)

In [0]:
matrix_data.shape
matrixData2 = matrix_data.copy()

In [0]:
t = np.array(matrix_data.shape)

In [0]:
# 각 벡터에서 평균을 빼주는..피어쓴...
t = np.array(matrix_data.shape)
n = t[0]
m = t[1]
for i in range(0,n):
  a=np.mean(matrix_data[i])
  #print(a)
  for j in range (0,m):
    matrixData2[i][j] -= a


In [0]:
def cos_sim_AB(a, b, Data):
    doc1 = np.array(Data[a:a+1])
    doc2 = np.array(Data[b:b+1])
    doc2 = doc2.reshape(24,1)
    return dot(doc1,doc2)/(norm(doc1)*norm(doc2))
  
def cos_sim_AB_MATRIX(a,b,Matrix):
  doc1 = Matrix[a:a+1]
  doc2 = Matrix[b:b+1]
  doc2 = doc2.reshape(24,1)
  return dot(doc1,doc2)/(norm(doc1)*norm(doc2))

def loc_sim_A(a,Matrix):
  doc1 = Matrix[a:a+1]
  t = Matrix.shape
  for i in range(0,t[0]):
    doc2 = Matrix[i:i+1]
    doc2 = doc2.reshape(24,1)
    sim = dot(doc1,doc2)/(norm(doc1)*norm(doc2))
    loc = indices[i]
    print("%s : %lf"%(loc,sim))

In [0]:
data

기준년월      지번코드  ...  22시~23시 유동인구 비율  23시~00시 유동인구 비율
0      201510  다다10C02A  ...     1.126810e-03     1.143921e-03
1      201510  다다09A03C  ...     1.160652e-03     1.049885e-03
2      201510  다다09D02C  ...     2.506180e-03     2.391745e-03
3      201510  다다09D02D  ...     1.316615e-03     1.293471e-03
4      201510  다다09C02C  ...     2.874693e-03     2.869880e-03
5      201510  다다09C02D  ...     1.442161e-03     1.443177e-03
6      201510  다다09D02B  ...     2.406056e-03     2.294484e-03
7      201510  다다09B02C  ...     8.526610e-04     8.445740e-04
8      201510  다다09C02B  ...     3.942266e-03     3.907714e-03
9      201510  다다09A03B  ...     1.091178e-03     9.912180e-04
10     201510  다다10D02A  ...     1.382101e-03     1.389955e-03
11     201510  다다09B02D  ...     8.488260e-04     8.611380e-04
12     201510  다나11C73D  ...     1.634410e-04     1.624330e-04
13     201510  다나11D73D  ...     2.806380e-04     2.806170e-04
14     201510  다나11A73A  ...     7.850000e-05     7.350000e-05
15     201510  다나12A73A  ...     3.272390e-04     3.735920e-04
16     201510  다나12C72A  ...     2.756740e-04     3.056150e-04
17     201510  다나12B72B  ...     3.172990e-04     3.512440e-04
18     201510  다나12D72B  ...     6.056320e-04     6.539810e-04
19     201510  다나12C73B  ...     1.746819e-03     1.838414e-03
20     201510  다나12B73B  ...     9.387700e-04     1.081773e-03
21     201510  다나12D73B  ...     1.882692e-03     1.730619e-03
22     201510  다나12C73C  ...     4.446470e-03     4.743799e-03
23     201510  다나12C72B  ...     2.920110e-04     3.140120e-04
24     201510  다나12D73A  ...     6.842150e-04     6.883530e-04
25     201510  다나12B73C  ...     2.933303e-03     3.219360e-03
26     201510  다나11B73D  ...     2.548530e-04     2.882370e-04
27     201510  다나12D72A  ...     3.329050e-04     3.812130e-04
28     201510  다나11A73D  ...     2.648510e-04     3.008910e-04
29     201510  다나12A73B  ...     1.016927e-03     1.135999e-03
...       ...       ...  ...              ...              ...
16656  201510  나나89D79A  ...     4.970000e-07     6.300000e-07
16657  201510  나나88C79D  ...     1.560000e-06     1.160000e-06
16658  201510  나나91A81B  ...     8.890000e-07     6.300000e-07
16659  201510  나나96A80A  ...     7.310000e-07     5.300000e-07
16660  201510  나나87B80A  ...     1.750000e-06     2.510000e-06
16661  201510  나나95B81D  ...     1.420000e-06     1.150000e-06
16662  201510  나나98B80B  ...     5.610000e-07     4.930000e-07
16663  201510  나나98A83D  ...     2.040000e-06     1.850000e-06
16664  201510  나나93A78C  ...     5.430000e-06     4.290000e-06
16665  201510  나나89C79C  ...     1.390000e-06     1.020000e-06
16666  201510  나나94A83D  ...     3.920000e-07     6.210000e-07
16667  201510  나나87B78D  ...     1.990000e-07     2.830000e-07
16668  201510  나나91A75C  ...     1.590000e-05     1.250000e-05
16669  201510  나나94B75B  ...     3.840000e-06     3.020000e-06
16670  201510  나나92C73C  ...     1.390000e-06     1.770000e-06
16671  201510  나나97D83B  ...     9.360000e-07     8.130000e-07
16672  201510  나나90A77C  ...     1.740000e-06     1.220000e-06
16673  201510  나나89D72B  ...     2.190000e-06     1.790000e-06
16674  201510  나나93B75D  ...     1.810000e-06     1.450000e-06
16675  201510  나나95A83C  ...     2.840000e-06     2.130000e-06
16676  201510  나나92C80D  ...     1.100000e-06     7.860000e-07
16677  201510  나나92D74A  ...     8.400000e-06     6.510000e-06
16678  201510  나나92A72D  ...     5.500000e-06     4.310000e-06
16679  201510  나나92D75D  ...     2.300000e-06     1.790000e-06
16680  201510  나나87A73C  ...     3.550000e-06     2.810000e-06
16681  201510  나나91B72B  ...     2.470000e-06     2.010000e-06
16682  201510  나나90C74A  ...     4.130000e-06     3.360000e-06
16683  201510  나나87D71A  ...     5.640000e-06     5.240000e-06
16684  201510  나나94B74C  ...     3.160000e-06     2.450000e-06
16685  201510  나나92B83A  ...     1.360000e-06     1.250000e-06

[16686 rows x 50 columns]

In [0]:
loc_sim_A(3,matrixData2)

0 : 0.480534
1 : 0.649515
2 : 0.806084
3 : 1.000000
4 : 0.926586
5 : 0.971090
6 : 0.770759
7 : 0.849753
8 : 0.829752
9 : 0.584354
10 : 0.833336
11 : 0.870169
12 : 0.244505
13 : 0.528361
14 : -0.024608
15 : 0.262625
16 : 0.276148
17 : 0.281409
18 : 0.342778
19 : 0.367699
20 : 0.273407
21 : 0.022777
22 : 0.337632
23 : 0.368234
24 : 0.501205
25 : 0.295453
26 : 0.276215
27 : 0.267412
28 : 0.277645
29 : 0.278940
30 : -0.170121
31 : 0.473758
32 : 0.369275
33 : 0.404591
34 : 0.288706
35 : 0.390674
36 : 0.269704
37 : -0.061432
38 : 0.341841
39 : 0.300550
40 : 0.265170
41 : 0.492749
42 : 0.335621
43 : 0.271152
44 : 0.282364
45 : -0.176344
46 : 0.004857
47 : 0.226073
48 : 0.318609
49 : 0.284491
50 : 0.403409
51 : 0.069139
52 : -0.362761
53 : -0.210873
54 : -0.328403
55 : -0.119062
56 : 0.192560
57 : -0.354024
58 : -0.354027
59 : -0.187713
60 : -0.342625
61 : -0.356722
62 : 0.182740
63 : 0.034877
64 : -0.300178
65 : 0.197621
66 : -0.236375
67 : -0.297765
68 : -0.347618
69 : -0.297936
70 : -0.1722

In [0]:
cos_sim_AB_MATRIX(2267,16232,matrixData2)

array([[-0.27100108]])

In [0]:
n = len(data)

for i in range(1,n-1):
  for j in range(i+1,n):
    print(cos_sim_AB_MATRIX(i,j,matrixData2))

[[0.96297684]]
[[0.64951542]]
[[0.78052243]]
[[0.48749611]]
[[0.97150181]]
[[0.84945538]]
[[0.88114234]]
[[0.98925931]]
[[0.19671987]]
[[0.23907472]]
[[0.39046325]]
[[0.18149184]]
[[0.37614648]]
[[-0.17004692]]
[[-0.13395466]]
[[-0.13426005]]
[[-0.12311876]]
[[-0.12906442]]
[[-0.187993]]
[[0.34459938]]
[[-0.11195043]]
[[-0.12576091]]
[[0.12948969]]
[[-0.14496863]]
[[-0.1695537]]
[[-0.17373115]]
[[-0.17434531]]
[[-0.1658575]]
[[0.3579331]]
[[-0.24490353]]
[[-0.21805068]]
[[-0.21032354]]
[[-0.13185185]]
[[0.18656726]]
[[-0.18103893]]
[[0.42088051]]
[[-0.10256305]]
[[-0.19043098]]
[[-0.17429411]]
[[0.15202672]]
[[-0.08817913]]
[[-0.18639066]]
[[-0.15975145]]
[[0.42177214]]
[[0.37155201]]
[[-0.16142819]]
[[-0.11721913]]
[[-0.07513981]]
[[-0.18108779]]
[[0.40196758]]
[[0.05900931]]
[[-0.31013789]]
[[-0.07724612]]
[[-0.41558781]]
[[-0.41689298]]
[[0.03086448]]
[[0.00266744]]
[[-0.21536073]]
[[0.02018074]]
[[0.02173941]]
[[-0.41199743]]
[[-0.40270817]]
[[-0.11982714]]
[[-0.41089524]]
[[-0.226

KeyboardInterrupt: ignored

In [0]:
len(data)

16686